export const crearPartida = 'http://nerks.net:7003/partida/crear'
//export const crearPartida = 'http://10.0.2.2:8080/partida/crear'
export const actualizarPartida = 'http://nerks.net:7003/partida/actualizar'
//export const actualizarPartida = 'http://10.0.2.2:8080/partida/actualizar'
export const unirPartida = 'http://nerks.net:7003/partida/unirJugador'
//export const unirPartida = 'http://10.0.2.2:8080/partida/unirJugador'
export const lanzarDados = 'http://nerks.net:7003/partida/lanzarDados'
//export const lanzarDados = 'http://10.0.2.2:8080/partida/lanzarDados'
export const listaJugadores = 'http://nerks.net:7003/partida/listaJugadores'
//export const listaJugadores = 'http://10.0.2.2:8080/partida/listaJugadores'
export const comprarAsignatura = 'http://nerks.net:7003/partida/comprar' //put
export const infoAsignatura = 'http://nerks.net:7003/partida/infoAsignatura' //put